CreateConVar("randomat_speedracer_delay",                5, FCVAR_REPLICATED, "Time (s) before each new location is revealed",                         1, 60)
CreateConVar("randomat_speedracer_timer_initial",        45, FCVAR_REPLICATED, "Time limit (s) to reach the first location",                            1, 240)
CreateConVar("randomat_speedracer_timer",                45, FCVAR_REPLICATED, "Time limit (s) to reach subsequent locations",                          1, 240)
CreateConVar("randomat_speedracer_autoadvance",          1,  FCVAR_REPLICATED, "Whether to skip the remaining timer if everyone reaches the  location", 0, 1)
CreateConVar("randomat_speedracer_kill_failures",        1,  FCVAR_REPLICATED, "Whether to kill players who don't reach the location in time",          0, 1)
CreateConVar("randomat_speedracer_reward_first_success", 1,  FCVAR_REPLICATED, "Whether to reward the first player to reach the location in time",      0, 1)
CreateConVar("randomat_speedracer_reward_success",       0,  FCVAR_REPLICATED, "Whether to reward all players who reach the location in time",          0, 1)
CreateConVar("randomat_speedracer_punish_failures",      0,  FCVAR_REPLICATED, "Whether to punish players who don't reach the location in time",        0, 1)
CreateConVar("randomat_speedracer_distance",             6,  FCVAR_REPLICATED, "Radius (m) of the target area",                                         1, 20)