JoelRdmt = JoelRdmt or {}

CreateConVar("randomat_solemusic_pitch_enable", 1, {FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_NOTIFY}, "Whether to shift pitch based on movement speed")
CreateConVar("randomat_solemusic_pitch_scale", 1, {FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_NOTIFY}, "Scale of pitch change vs speed difference", 0, 10)
CreateConVar("randomat_solemusic_pitch_min", 50, {FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_NOTIFY}, "Lower pitch shift limit", 1, 255)
CreateConVar("randomat_solemusic_pitch_max", 255, {FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_NOTIFY}, "Upper pitch shift limit", 1, 255)
CreateConVar("randomat_solemusic_play_backwards", 1, {FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_NOTIFY}, "Whether songs should play backwards when players move backwards")

JoelRdmt.SoleMusicSongs = {
    {
        name = "nyancat",
        bpm = 285,
        music = {
            {note = "X", len = 0.000000001},
            {note = "G4", len = 1},
            {note = "A4", len = 1},
            {note = "D#4", len = 0.5},
            {note = "E4", len = 1},
            {note = "C4", len = 0.5},
            {note = "D#4", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "C4", len = 1},
            {note = "C4", len = 1},
            {note = "D4", len = 1},
            {note = "D#4", len = 1},
            {note = "D#4", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "G4", len = 0.5},
            {note = "A4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "G4", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "E4", len = 1},
            {note = "G4", len = 1},
            {note = "A4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "G4", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "D#4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "D#4", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "D#4", len = 1},
            {note = "C4", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "G4", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "D#4", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "D4", len = 1},
            {note = "C4", len = 1},
            {note = "C4", len = 1},
            ---------------------------------
            {note = "C4", len = 1},
            {note = "G3", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "C4", len = 1},
            {note = "G3", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "F4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "F4", len = 0.5},
            {note = "G4", len = 0.5},
            {note = "C4", len = 1},
            {note = "C4", len = 1},
            {note = "G3", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "F4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "E3", len = 0.5},
            {note = "F3", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "C4", len = 1},
            {note = "G3", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "C4", len = 1},
            {note = "G3", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "C4", len = 1},
            {note = "C4", len = 0.5},
            {note = "B3", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "C4", len = 0.5},
            {note = "F4", len = 0.5},
            {note = "E4", len = 0.5},
            {note = "F4", len = 0.5},
            {note = "G4", len = 0.5},
            {note = "C4", len = 1},
            {note = "D4", len = 1},
        },
    },
    {
        name = "imperialmarch",
        bpm = 100,
        music = {
            --------------------------------- 1
            {note = "X", len = 0.000000001},
            {note = "G3", len = 0.95},
            {note = "X", len = 0.05},
            {note = "G3", len = 0.95},
            {note = "X", len = 0.05},
            {note = "G3", len = 0.95},
            {note = "X", len = 0.05},
            {note = "D#3", len = 0.7},
            {note = "X", len = 0.05},
            {note = "A#3", len = 0.25},
            --------------------------------- 2
            {note = "G3", len = 0.95},
            {note = "X", len = 0.05},
            {note = "D#3", len = 0.7},
            {note = "X", len = 0.05},
            {note = "A#3", len = 0.25},
            {note = "G3", len = 1.5},
            {note = "X", len = 0.5},
            --------------------------------- 3
            {note = "D4", len = 0.95},
            {note = "X", len = 0.05},
            {note = "D4", len = 0.95},
            {note = "X", len = 0.05},
            {note = "D4", len = 0.95},
            {note = "X", len = 0.05},
            {note = "D#4", len = 0.7},
            {note = "X", len = 0.05},
            {note = "A#3", len = 0.25},
            --------------------------------- 4
            {note = "F#3", len = 0.95},
            {note = "X", len = 0.05},
            {note = "D#3", len = 0.7},
            {note = "X", len = 0.05},
            {note = "A#3", len = 0.25},
            {note = "G3", len = 1.5},
            {note = "X", len = 0.5},
            --------------------------------- 5
            {note = "G4", len = 0.95},
            {note = "X", len = 0.05},
            {note = "G3", len = 0.7},
            {note = "X", len = 0.05},
            {note = "G3", len = 0.25},
            {note = "G4", len = 0.95},
            {note = "X", len = 0.05},
            {note = "F#4", len = 0.7},
            {note = "X", len = 0.05},
            {note = "F4", len = 0.25},
            --------------------------------- 6
            {note = "E4", len = 0.25},
            {note = "D#4", len = 0.25},
            {note = "E4", len = 0.5},
            {note = "X", len = 0.5},
            {note = "G#3", len = 0.5},
            {note = "C#4", len = 0.95},
            {note = "X", len = 0.05},
            {note = "C4", len = 0.7},
            {note = "X", len = 0.05},
            {note = "B3", len = 0.25},
            --------------------------------- 7
            {note = "A#3", len = 0.25},
            {note = "A3", len = 0.25},
            {note = "A#3", len = 0.5},
            {note = "X", len = 0.5},
            {note = "D#3", len = 0.5},
            {note = "F#3", len = 0.95},
            {note = "X", len = 0.05},
            {note = "D#3", len = 0.7},
            {note = "X", len = 0.05},
            {note = "F#3", len = 0.25},
            --------------------------------- 8
            {note = "A#3", len = 0.95},
            {note = "X", len = 0.05},
            {note = "G3", len = 0.7},
            {note = "X", len = 0.05},
            {note = "A#3", len = 0.25},
            {note = "D4", len = 1.5},
            {note = "X", len = 0.5},
            --------------------------------- 9
            {note = "G4", len = 0.95},
            {note = "X", len = 0.05},
            {note = "G3", len = 0.7},
            {note = "X", len = 0.05},
            {note = "G3", len = 0.25},
            {note = "G4", len = 0.95},
            {note = "X", len = 0.05},
            {note = "F#4", len = 0.7},
            {note = "X", len = 0.05},
            {note = "F4", len = 0.25},
            --------------------------------- 10
            {note = "E4", len = 0.25},
            {note = "D#4", len = 0.25},
            {note = "E4", len = 0.5},
            {note = "X", len = 0.5},
            {note = "G#3", len = 0.5},
            {note = "C#4", len = 0.95},
            {note = "C4", len = 0.7},
            {note = "X", len = 0.05},
            {note = "B3", len = 0.25},
            --------------------------------- 11
            {note = "A#3", len = 0.25},
            {note = "A3", len = 0.25},
            {note = "A#3", len = 0.5},
            {note = "X", len = 0.5},
            {note = "D#3", len = 0.5},
            {note = "F#3", len = 0.95},
            {note = "X", len = 0.05},
            {note = "D#3", len = 0.7},
            {note = "X", len = 0.05},
            {note = "A#3", len = 0.25},
            --------------------------------- 12
            {note = "G3", len = 0.95},
            {note = "X", len = 0.05},
            {note = "D#3", len = 0.7},
            {note = "X", len = 0.05},
            {note = "A#3", len = 0.25},
            {note = "G3", len = 1.5},
            {note = "X", len = 0.5}
            ---------------------------------
        },
    },
    {
        name = "pinkpanther",
        bpm = 120,
        music = {
            {note = "X", len = 0.000000001},
            {note = "D#3", len = 0.35},
            --------------------------------- 5
            {note = "E3", len = 0.6},
            {note = "X", len = 0.4},
            {note = "X", len = 0.65},
            {note = "F#3", len = 0.35},
            {note = "G3", len = 0.6},
            {note = "X", len = 1.05},
            {note = "D#3", len = 0.35},
            --------------------------------- 6
            {note = "E3", len = 0.5},
            {note = "X", len = 0.15},
            {note = "F#3", len = 0.35},
            {note = "G3", len = 0.5},
            {note = "X", len = 0.15},
            {note = "C4", len = 0.35},
            {note = "B3", len = 0.5},
            {note = "X", len = 0.15},
            {note = "E3", len = 0.35},
            {note = "G3", len = 0.5 },
            {note = "X", len = 0.15},
            {note = "B3", len = 0.35},
            --------------------------------- 7
            {note = "A#3", len = 2.3},
            {note = "A3", len = 0.3},
            {note = "G3", len = 0.3},
            {note = "E3", len = 0.3},
            {note = "D3", len = 0.3},
            --------------------------------- 8
            {note = "E3", len = 1.48},
            {note = "X", len = 2.17},
            {note = "D#3", len = 0.35},
            --------------------------------- 9
            {note = "E3", len = 0.6},
            {note = "X", len = 0.4},
            {note = "X", len = 0.65},
            {note = "F#3", len = 0.35},
            {note = "G3", len = 0.6},
            {note = "X", len = 1.05},
            {note = "D#3", len = 0.35},
            --------------------------------- 10
            {note = "E3", len = 0.5},
            {note = "X", len = 0.15},
            {note = "F#3", len = 0.35},
            {note = "G3", len = 0.5},
            {note = "X", len = 0.15},
            {note = "C4", len = 0.35},
            {note = "B3", len = 0.5},
            {note = "X", len = 0.15},
            {note = "G3", len = 0.35},
            {note = "B3", len = 0.5 },
            {note = "X", len = 0.15},
            {note = "E4", len = 0.35},
            --------------------------------- 11
            {note = "D#4", len = 7.7},
            --------------------------------- 12
            {note = "D#3", len = 0.35},
            --------------------------------- 13
            {note = "E3", len = 0.6},
            {note = "X", len = 0.4},
            {note = "X", len = 0.65},
            {note = "F#3", len = 0.35},
            {note = "G3", len = 0.6},
            {note = "X", len = 1.05},
            {note = "D#3", len = 0.35},
            --------------------------------- 14
            {note = "E3", len = 0.5},
            {note = "X", len = 0.15},
            {note = "F#3", len = 0.35},
            {note = "G3", len = 0.5},
            {note = "X", len = 0.15},
            {note = "C4", len = 0.35},
            {note = "B3", len = 0.5},
            {note = "X", len = 0.15},
            {note = "E3", len = 0.35},
            {note = "G3", len = 0.5 },
            {note = "X", len = 0.15},
            {note = "B3", len = 0.35},
            --------------------------------- 15
            {note = "A#3", len = 2.3},
            {note = "A3", len = 0.3},
            {note = "G3", len = 0.3},
            {note = "E3", len = 0.3},
            {note = "D3", len = 0.3},
            --------------------------------- 16
            {note = "E3", len = 4},
            --------------------------------- 17
            {note = "X", len = 1},
            {note = "E4", len = 0.7},
            {note = "D4", len = 0.3},
            {note = "B3", len = 0.7},
            {note = "A3", len = 0.3},
            {note = "G3", len = 0.7},
            {note = "E3", len = 0.3},
            --------------------------------- 18
            {note = "A#3", len = 0.2},
            {note = "A3", len = 0.8},
            {note = "A#3", len = 0.2},
            {note = "A3", len = 0.8},
            {note = "A#3", len = 0.2},
            {note = "A3", len = 0.8},
            {note = "A#3", len = 0.2},
            {note = "A3", len = 0.8},
            --------------------------------- 19
            {note = "G3", len = 0.3},
            {note = "E3", len = 0.3},
            {note = "D3", len = 0.3},
            {note = "E3", len = 0.7},
            {note = "E3", len = 5.3},
            --------------------------------- 20
            {note = "X", len = 0.65},
        }
    },
    {
        name = "nevergonnagiveyouup",
        bpm = 128,
        music = {
            {note = "X", len = 0.000000001},
            --------------------------------- 5
            {note = "X", len = 1},
            {note = "E3", len = 0.5},
            {note = "F#3", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "F#3", len = 0.75},
            --------------------------------- 6
            {note = "E3", len = 0.25},
            {note = "D3", len = 2.5},
            {note = "X", len = 1},
            --------------------------------- 7
            {note = "X", len = 0.5},
            {note = "E3", len = 0.5},
            {note = "E3", len = 0.5},
            {note = "F#3", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "E3", len = 1},
            {note = "D3", len = 0.5},
            --------------------------------- 8
            {note = "D4", len = 0.5},
            {note = "X", len = 0.5},
            {note = "D4", len = 0.5},
            {note = "A3", len = 1.5},
            {note = "X", len = 1},
            --------------------------------- 9
            {note = "X", len = 0.5},
            {note = "E3", len = 0.5},
            {note = "E3", len = 0.5},
            {note = "F#3", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "E3", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "A3", len = 0.5},
            --------------------------------- 10
            {note = "X", len = 0.5},
            {note = "F#3", len = 0.5},
            {note = "E3", len = 0.5},
            {note = "D3", len = 1.5},
            {note = "X", len = 1},
            --------------------------------- 10
            {note = "X", len = 0.5},
            {note = "E3", len = 0.5},
            {note = "E3", len = 0.5},
            {note = "F#3", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "E3", len = 0.5},
            {note = "D3", len = 1},
            --------------------------------- 11
            {note = "A3", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "B3", len = 0.5},
            {note = "A3", len = 1},
            {note = "X", len = 1},
            --------------------------------- 12
            {note = "G3", len = 2.5},
            {note = "A3", len = 0.5},
            {note = "B3", len = 0.5},
            {note = "G3", len = 0.5},
            --------------------------------- 13
            {note = "A3", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "B3", len = 0.5},
            {note = "A3", len = 1},
            {note = "D3", len = 1},
            --------------------------------- 14
            {note = "X", len = 2},
            {note = "E3", len = 0.5},
            {note = "F#3", len = 0.5},
            {note = "G3", len = 0.5},
            {note = "E3", len = 0.5},
            --------------------------------- 15
            {note = "X", len = 0.5},
            {note = "A3", len = 0.5},
            {note = "B3", len = 0.5},
            {note = "A3", len = 1.5},
            {note = "D3", len = 0.25},
            {note = "E3", len = 0.25},
            {note = "G3", len = 0.25},
            {note = "E3", len = 0.25},
            --------------------------------- 16
            {note = "B3", len = 0.75},
            {note = "B3", len = 0.75},
            {note = "A3", len = 1.5},
            {note = "D3", len = 0.25},
            {note = "E3", len = 0.25},
            {note = "G3", len = 0.25},
            {note = "E3", len = 0.25},
            --------------------------------- 17
            {note = "A3", len = 0.75},
            {note = "A3", len = 0.75},
            {note = "G3", len = 0.75},
            {note = "F#3", len = 0.25},
            {note = "E3", len = 0.5},
            {note = "D3", len = 0.25},
            {note = "E3", len = 0.25},
            {note = "G3", len = 0.25},
            {note = "E3", len = 0.25},
            --------------------------------- 18
            {note = "G3", len = 1},
            {note = "A3", len = 0.5},
            {note = "F#3", len = 0.75},
            {note = "E3", len = 0.25},
            {note = "D3", len = 1},
            {note = "D3", len = 0.5},
            --------------------------------- 18
            {note = "A3", len = 1},
            {note = "G3", len = 2},
            {note = "D3", len = 0.25},
            {note = "E3", len = 0.25},
            {note = "G3", len = 0.25},
            {note = "E3", len = 0.25},
            --------------------------------- 19
            {note = "B3", len = 0.75},
            {note = "B3", len = 0.75},
            {note = "A3", len = 1.5},
            {note = "D3", len = 0.25},
            {note = "E3", len = 0.25},
            {note = "G3", len = 0.25},
            {note = "E3", len = 0.25},
            --------------------------------- 20
            {note = "D4", len = 1},
            {note = "F#3", len = 0.5},
            {note = "G3", len = 0.75},
            {note = "F#3", len = 0.25},
            {note = "E3", len = 0.5},
            {note = "D3", len = 0.25},
            {note = "E3", len = 0.25},
            {note = "G3", len = 0.25},
            {note = "E3", len = 0.25},
            --------------------------------- 21
            {note = "G3", len = 1},
            {note = "A3", len = 0.5},
            {note = "F#3", len = 0.75},
            {note = "E3", len = 0.25},
            {note = "D3", len = 1},
            {note = "D3", len = 0.5},
            --------------------------------- 22
            {note = "A3", len = 1},
            {note = "G3", len = 2},
            {note = "X", len = 1},
        }
    }
}